// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy929j0rinyl3axa4r7fqg2CnfTHWclWI',
    appId: '1:244599225996:web:678ec77fdcb20084c085a9',
    messagingSenderId: '244599225996',
    projectId: 'storage-docs-c61bd',
    authDomain: 'storage-docs-c61bd.firebaseapp.com',
    storageBucket: 'storage-docs-c61bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpGu5qEnprXdMoT1tpgUdgR7ILbFdElVs',
    appId: '1:244599225996:android:6152d4a7066cef00c085a9',
    messagingSenderId: '244599225996',
    projectId: 'storage-docs-c61bd',
    storageBucket: 'storage-docs-c61bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-dJwkYVuWGILniXYVtW_9c8zLypmW6ik',
    appId: '1:244599225996:ios:327d03f9ae99789dc085a9',
    messagingSenderId: '244599225996',
    projectId: 'storage-docs-c61bd',
    storageBucket: 'storage-docs-c61bd.appspot.com',
    iosClientId: '244599225996-3neclgehi6smp0ga4r86ifd84c57vvrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.movilProyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-dJwkYVuWGILniXYVtW_9c8zLypmW6ik',
    appId: '1:244599225996:ios:327d03f9ae99789dc085a9',
    messagingSenderId: '244599225996',
    projectId: 'storage-docs-c61bd',
    storageBucket: 'storage-docs-c61bd.appspot.com',
    iosClientId: '244599225996-3neclgehi6smp0ga4r86ifd84c57vvrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.movilProyecto',
  );
}
